AllCops:
  Exclude:
    - "vendor/**/*"
    - "lib/bq_factory/version.rb"
    - "Rakefile"
    - "Gemfile"
    - "Guardfile"
    - "bq_factory.gemspec"
  DisplayCopNames: true

Rails:
  Enabled: false

##################### Style ##################################

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/SignalException:
  Enabled: false

##################### Metrics ##################################

Metrics/AbcSize:
  Max: 30

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20
