language: ruby
rvm:
  - 2.1
  - 2.2
  - 2.3.0
  - ruby-head

before_install: gem install bundler -v "~> 1.10"
bundler_args: "--jobs=2"
cache: bundler

script:
  - ruby --version
  - bundle install
  - bundle exec rspec

gemfile:
  - gemfiles/google-api-client_0-9.gemspec
  - gemfiles/google-api-client_0-8.gemspec

matrix:
  allow_failures:
    - rvm: ruby-head
